---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cwl-default-worker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cwl-default-worker
    spec:
      containers:
      - name: cwl-default-worker
        image: {{WORKFLOW_ENGINE_CWL_IMAGE}}
        {%- if DEPLOYMENT != 'prod' %}
        tty: true
        stdin: true
        {% endif %}
        imagePullPolicy: {{IMAGE_PULL_POLICY}}
        env:
        - name: QUEUE_ENV
          value: cwl-default-queue
        - name: REANA_WORKFLOW_ENGINE_EXPERIMENT
          value: default
        - name: SHARED_VOLUME_PATH
          value: /reana
        {% set environment=RWECWL_ENVIRONMENT %}
        {% for envvar in environment %}
        {% for key, value in envvar.items() %}
        - name: {{key}}
          value: "{{value}}"
        {% endfor %}
        {% endfor %}
        volumeMounts:
        - name: default-shared-volume
          mountPath: /reana
        {% set mountpoints=RWECWL_MOUNTPOINTS %}
        {% for mount in mountpoints %}
        - mountPath: {{mount['path'].split(':')[1]}}
          name: {{mount['name']}}
        {% endfor %}
      volumes:
      - name: default-shared-volume
        {%- if DEPLOYMENT == 'prod' %}
        cephfs:
          monitors:
          {% for monitor in CEPHFS_MONITORS  %}
           - {{monitor}}
          {% endfor %}
          path: "{{ROOT_PATH}}"
          user: {{CEPHFS_USER}}
          secretRef:
            name: {{CEPHFS_SECRET_NAME}}
          readOnly: {{CEPHFS_READONLY}}
        {% else %}
        hostPath:
            path: "{{ROOT_PATH}}"
        {% endif %}
      {% for mount in mountpoints %}
      - name: {{mount['name']}}
        {{mount['type']}}:
          path: {{mount['path'].split(':')[0]}}
      {% endfor %}
