---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: job-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: job-controller
    spec:
      containers:
      - name: job-controller
        image: {{JOB_CONTROLLER_IMAGE}}
        {% if DEPLOYMENT != 'prod' %}
        command: ["flask", "run", "-h", "0.0.0.0"]
        {% endif %}
        imagePullPolicy: {{IMAGE_PULL_POLICY}}
        {%- if DEPLOYMENT != 'prod' %}
        tty: true
        stdin: true
        {% endif %}
        ports:
        - containerPort: 5000
          name: http
        volumeMounts:
        - name: svaccount
          mountPath: "/var/run/secrets/kubernetes.io/serviceaccount"
        - name: reana-shared-volume
          mountPath: "/reana"
        {%- if DEPLOYMENT == 'prod' %}
        - name: cms-cvmfs-volume
          mountPath: /cvmfs/cms.cern.ch
        - name: atlas-cvmfs-volume
          mountPath: /cvmfs/atlas.cern.ch
        - name: alice-cvmfs-volume
          mountPath: /cvmfs/alice.cern.ch
        - name: lhcb-cvmfs-volume
          mountPath: /cvmfs/lhcb.cern.ch
        {% endif %}
        {% set mountpoints=RJC_MOUNTPOINTS %}
        {% for mount in mountpoints %}
        - mountPath: {{mount['path'].split(':')[1]}}
          name: {{mount['name']}}
        {% endfor %}
        env:
        - name: SHARED_VOLUME_PATH_ROOT
          value: "{{ROOT_PATH}}"
        - name: REANA_STORAGE_BACKEND
          value: {% if DEPLOYMENT == 'prod' %}CEPHFS{% else %}LOCAL{% endif %}
        {% set environment=RJC_ENVIRONMENT %}
        {% for envvar in environment %}
        {% for key, value in envvar.items() %}
        - name: {{key}}
          value: "{{value}}"
        {% endfor %}
        {% endfor %}
      volumes:
      - name: reana-shared-volume
        {% if DEPLOYMENT == 'prod' %}
        persistentVolumeClaim:
          claimName: manila-cephfs-pvc
          readOnly: false
      - name: cms-cvmfs-volume
        persistentVolumeClaim:
          claimName: csi-cvmfs-cms-pvc
          readOnly: true
      - name: atlas-cvmfs-volume
        persistentVolumeClaim:
          claimName: csi-cvmfs-atlas-pvc
          readOnly: true
      - name: lhcb-cvmfs-volume
        persistentVolumeClaim:
          claimName: csi-cvmfs-lhcb-pvc
          readOnly: true
      - name: alice-cvmfs-volume
        persistentVolumeClaim:
          claimName: csi-cvmfs-alice-pvc
          readOnly: true
        {% else %}
        hostPath:
          path: {{ROOT_PATH}}
        {% endif %}
      - name: svaccount
        secret:
          secretName: {{K8S_APISERVER_SECRET}}
      {% for mount in mountpoints %}
      - name: {{mount['name']}}
        {{mount['type']}}:
          path: {{mount['path'].split(':')[0]}}
      {% endfor %}
