---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: job-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: job-controller
    spec:
      containers:
      - name: job-controller
        image: {{JOB_CONTROLLER_IMAGE}}
        {% if DEPLOYMENT != 'prod' %}
        command: ["/bin/sh","-c"]
        args: ["python reana_job_controller/app.py"]
        {% endif %}
        imagePullPolicy: {{IMAGE_PULL_POLICY}}
        {%- if DEPLOYMENT != 'prod' %}
        tty: true
        stdin: true
        {% endif %}
        ports:
        - containerPort: 5000
          name: http
        volumeMounts:
        - name: svaccount
          mountPath: "/var/run/secrets/kubernetes.io/serviceaccount"
        {% set mountpoints=RJC_MOUNTPOINTS %}
        {% for mount in mountpoints %}
        - mountPath: {{mount['path'].split(':')[1]}}
          name: {{mount['name']}}
        {% endfor %}
        env:
        - name: SHARED_VOLUME_PATH_ROOT
          value: "{{ROOT_PATH}}"
        - name: REANA_STORAGE_BACKEND
          value: {% if DEPLOYMENT == 'prod' %}CEPHFS{% else %}LOCAL{% endif %}
        {% set environment=RJC_ENVIRONMENT %}
        {% for envvar in environment %}
        {% for key, value in envvar.items() %}
        - name: {{key}}
          value: "{{value}}"
        {% endfor %}
        {% endfor %}
      volumes:
      - name: svaccount
        secret:
          secretName: {{K8S_APISERVER_SECRET}}
      {% for mount in mountpoints %}
      - name: {{mount['name']}}
        {{mount['type']}}:
          path: {{mount['path'].split(':')[0]}}
      {% endfor %}
