---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: {{SERVER_IMAGE}}
        {% if DEBUG %}
        command: ["/bin/sh","-c"]
        args: ["set -e; flask db init; flask users create_default info@reana.io; flask run --host=0.0.0.0"]
        tty: true
        stdin: true
        {% endif %}
        imagePullPolicy: {{IMAGE_PULL_POLICY}}
        volumeMounts:
        - mountPath: {{SHARED_VOLUME_PATH}}
          name: reana-shared-volume
        {%- if CVMFS %}
        - name: cms-cvmfs-volume
          mountPath: /cvmfs/cms.cern.ch
        - name: atlas-cvmfs-volume
          mountPath: /cvmfs/atlas.cern.ch
        - name: alice-cvmfs-volume
          mountPath: /cvmfs/alice.cern.ch
        - name: lhcb-cvmfs-volume
          mountPath: /cvmfs/lhcb.cern.ch
        {% endif %}
        {% set mountpoints=RS_MOUNTPOINTS %}
        {% for mount in mountpoints %}
        - mountPath: {{mount['path'].split(':')[1]}}
          name: {{mount['name']}}
        {% endfor %}
        ports:
        - containerPort: 5000
          name: http
        env:
        {% set environment=RS_ENVIRONMENT %}
        {% for envvar in environment %}
        {% for key, value in envvar.items() %}
        - name: {{key}}
          value: "{{value}}"
        {% endfor %}
        {% endfor %}
      - name: scheduler
        image: {{SERVER_IMAGE}}
        command: ["flask", "start-scheduler"]
        imagePullPolicy: {{IMAGE_PULL_POLICY}}
        volumeMounts:
        - mountPath: "/reana"
          name: reana-shared-volume
        {% set mountpoints=RS_MOUNTPOINTS %}
        {% for mount in mountpoints %}
        - mountPath: {{mount['path'].split(':')[1]}}
          name: {{mount['name']}}
        {% endfor %}
        env:
        {% set environment=RS_ENVIRONMENT %}
        {% for envvar in environment %}
        {% for key, value in envvar.items() %}
        - name: {{key}}
          value: "{{value}}"
        {% endfor %}
        {% endfor %}
      volumes:
      - name: reana-shared-volume
        {% if CEPHFS %}
        persistentVolumeClaim:
          claimName: manila-cephfs-pvc
          readOnly: false
        {% else %}
        hostPath:
          path: {{ROOT_PATH}}
        {% endif %}
        {% if CVMFS %}
      - name: cms-cvmfs-volume
        persistentVolumeClaim:
          claimName: csi-cvmfs-cms-pvc
          readOnly: true
      - name: atlas-cvmfs-volume
        persistentVolumeClaim:
          claimName: csi-cvmfs-atlas-pvc
          readOnly: true
      - name: lhcb-cvmfs-volume
        persistentVolumeClaim:
          claimName: csi-cvmfs-lhcb-pvc
          readOnly: true
      - name: alice-cvmfs-volume
        persistentVolumeClaim:
          claimName: csi-cvmfs-alice-pvc
          readOnly: true
        {% endif %}
      {% for mount in mountpoints %}
      - name: {{mount['name']}}
        {{mount['type']}}:
          path: {{mount['path'].split(':')[0]}}
      {% endfor %}
