---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: {{SERVER_IMAGE}}
        {% if DEPLOYMENT != 'prod' %}
        command: ["/bin/sh","-c"]
        args: ["flask db init; flask users create info@reana.io; flask run --host=0.0.0.0"]
        {% endif %}
        imagePullPolicy: {{IMAGE_PULL_POLICY}}
        {%- if DEPLOYMENT != 'prod' %}
        tty: true
        stdin: true
        {% endif %}
        volumeMounts:
        - mountPath: "/reana"
          name: reana-shared-volume
        {% set mountpoints=RS_MOUNTPOINTS %}
        {% for mount in mountpoints %}
        - mountPath: {{mount['path'].split(':')[1]}}
          name: {{mount['name']}}
        {% endfor %}
        ports:
        - containerPort: 5000
          name: http
        env:
        {% set environment=RS_ENVIRONMENT %}
        {% for envvar in environment %}
        {% for key, value in envvar.items() %}
        - name: {{key}}
          value: "{{value}}"
        {% endfor %}
        {% endfor %}
      volumes:
      - name: reana-shared-volume
        {% if DEPLOYMENT == 'prod' %}
        cephfs:
          monitors:
          {% for monitor in CEPHFS_MONITORS  %}
           - {{monitor}}
          {% endfor %}
          path: {{ROOT_PATH}}
          user: {{CEPHFS_USER}}
          secretRef:
            name: {{CEPHFS_SECRET_NAME}}
          readOnly: {{CEPHFS_READONLY}}
        {% else %}
        hostPath:
          path: {{ROOT_PATH}}
        {% endif %}
      {% for mount in mountpoints %}
      - name: {{mount['name']}}
        {{mount['type']}}:
          path: {{mount['path'].split(':')[0]}}
      {% endfor %}