---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: frontend
  {% if not DEBUG %}
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.entryPoints: "http,https"
  {% endif %}
spec:
  rules:
  - http:
      paths:
      - path: /api
        backend:
          serviceName: server
          servicePort: 80
      - path: /oauth
        backend:
          serviceName: server
          servicePort: 80
      - path: /account
        backend:
          serviceName: server
          servicePort: 80
      - path: /lost-password
        backend:
          serviceName: server
          servicePort: 80
      - path: /confirm
        backend:
          serviceName: server
          servicePort: 80
      - path: /login
        backend:
          serviceName: server
          servicePort: 80
      - path: /logout
        backend:
          serviceName: server
          servicePort: 80
      - path: /sign-up
        backend:
          serviceName: server
          servicePort: 80
      {% if UI %}
      - path: /
        backend:
          serviceName: ui
          servicePort: 80
      {%- endif %}
  {% if URL %}
    host: {{REANA_URL}}
  tls:
    - secretName: reana-ssl-secrets
  {% endif %}
